# "Bad Day" by Daniel Powter
print("Where is the moment we needed the most?")
print("You kick up the leaves, and the magic is lost")
print("You tell me your blue sky's faded to gray")
print("You tell me your passion's gone away")
print("And I don't need no carrying on")
print("You stand in the line just to hit a new low")
print("You're faking a smile with the coffee to go")
print("You fall into pieces every time")
print("And I don't need no carrying on")
print("Because you had a bad day")
print("You're taking one down")
print("You sing a sad song just to turn it around") # I love this line.
print("You say you don't know")
print("You tell me, Don't lie")
print("You work at a smile, and you go for a ride")
print("You had a bad day")
print("The camera don't lie")
print("You're coming back down, and you really don't mind")
print("You had a bad day")
print("You had a bad day")